os: linux

language: bash
services: docker

env:
  matrix:
    - VERSION=13
    - VERSION=11
    - VERSION=8
    - VM=hotspot
    - VM=openj9
    - PACKAGE=jdk
    - PACKAGE=jre

script: bash build_latest.sh $VERSION $VM $PACKAGE

stages:
  - linter
  - test

jobs:
  include:
    - stage: linter
      script: ./linter.sh
